spring:
  datasource:
    url: jdbc:mysql://localhost:3306/INFORME_O_SEU_BANCO?useSSL=false&serverTimezone=America/Sao_Paulo
    username: INFORME_O_USUARIO
    password: INFORME_A_SENHA
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect